### ISSUE TITLE
[Performance] Make these constant.

### ISSUE THREAD

**Issue by portlek** [IridiumLLC/IridiumColorAPI#1]
[Pattern.compile("<GR...](https://github.com/IridiumLLC/IridiumColorAPI/blob/master/src/main/java/com/iridium/iridiumcolorapi/IridiumColorAPI.java#L64)
[Pattern.compile("<SO...](https://github.com/IridiumLLC/IridiumColorAPI/blob/master/src/main/java/com/iridium/iridiumcolorapi/IridiumColorAPI.java#L72)
["Cannot get...](https://github.com/IridiumLLC/IridiumColorAPI/blob/master/src/main/java/com/iridium/iridiumcolorapi/IridiumColorAPI.java#L188)
["MC:"](https://github.com/IridiumLLC/IridiumColorAPI/blob/master/src/main/java/com/iridium/iridiumcolorapi/IridiumColorAPI.java#L191)
["SNAPSHOT"](https://github.com/IridiumLLC/IridiumColorAPI/blob/master/src/main/java/com/iridium/iridiumcolorapi/IridiumColorAPI.java#L191)

**Comment by PeachesMLG** [comment]
get Major version is only called once and then cached as a boolean. Ill cache the Patterns later :)
